'use client';

import { FormFieldWrapper } from '@/components/forms/common/FormFieldWrapper';
import { FormInput } from '@/components/forms/common/FormInput';
import { FormError } from '@/components/forms/components/FormError';
import { ServiceListItem } from '@/components/templates/ServicesTemplate/types';
import { Form } from '@/components/ui/form';
import { Textarea } from '@/components/ui/textarea';
import { Typography } from '@/components/ui/typography';
import { useEffect, useMemo, useState } from 'react';
import {
  BookingFormDateTimePicker,
  BookingFormExtraServices,
  BookingFormRadioGroup,
  BookingFormServiceCard,
} from './components';
import { BookingFormValues } from './schema';
import { useBookingForm } from './useBookingForm';

export type BookingFormProps = {
  service: ServiceListItem;
  extraServices?: ServiceListItem[];
  isLoadingExtraServices?: boolean;
  availablePaymentMethods?: { id: string; name: string }[];
  isLoadingPaymentMethods?: boolean;
  availableTimeSlots?: string[];
  isLoadingTimeSlots?: boolean;
  availableDays?: string[];
  selectedDate: Date | undefined;
  onSelectDate?: (date: Date | undefined) => void;
  onSubmitSuccess: (formData: BookingFormValues, totalPrice: number) => void;
  onSubmitStateChange?: (isSubmitting: boolean) => void;
  onFormDataChange?: (data: {
    timeSlot?: string;
    totalPrice: number;
    extraServices: ServiceListItem[];
    tipAmount?: number;
  }) => void;
  isCalendarLoading?: boolean;
  professionalTimezone?: string;
  clientTimezone?: string;
};

export function BookingForm({
  service,
  extraServices = [],
  isLoadingExtraServices = false,
  availablePaymentMethods = [],
  isLoadingPaymentMethods = false,
  availableTimeSlots,
  isLoadingTimeSlots = false,
  availableDays = [],
  selectedDate,
  onSelectDate,
  onSubmitSuccess,
  onSubmitStateChange,
  onFormDataChange,
  isCalendarLoading = false,
  professionalTimezone,
  clientTimezone,
}: BookingFormProps) {
  // Use local state for date to ensure component has control
  const [localSelectedDate, setLocalSelectedDate] = useState<Date | undefined>(
    selectedDate,
  );

  // Sync with parent when parent date changes
  useEffect(() => {
    if (selectedDate !== localSelectedDate) {
      setLocalSelectedDate(selectedDate);
      if (selectedDate) {
        form.setValue('date', selectedDate);
      }
    }
  }, [selectedDate]);

  const { form, calculateTotalPrice, onSubmit, isPending } = useBookingForm({
    onSubmit: async (data: BookingFormValues) => {
      // Call the onSubmitSuccess callback with the form data and price
      // The actual booking ID will be generated by the server
      onSubmitSuccess(data, calculateTotalPrice());
    },
    service,
    extraServices,
  });

  // Notify parent about submission state changes
  useEffect(() => {
    if (onSubmitStateChange) {
      onSubmitStateChange(isPending);
    }
  }, [isPending, onSubmitStateChange]);

  const totalPrice = useMemo(
    () => calculateTotalPrice(),
    [
      calculateTotalPrice,
      form.watch('extraServiceIds'),
      form.watch('tipAmount'),
    ],
  );

  // Payment method options
  const paymentOptions = useMemo(() => {
    if (availablePaymentMethods && availablePaymentMethods.length > 0) {
      return availablePaymentMethods.map((method) => ({
        value: method.id,
        label: method.name,
      }));
    }

    return [];
  }, [availablePaymentMethods]);

  // Get selected extra services for the datetime picker
  const selectedExtraServices = useMemo(() => {
    const selectedIds = form.watch('extraServiceIds') || [];
    return extraServices.filter((service) => selectedIds.includes(service.id));
  }, [extraServices, form.watch('extraServiceIds')]);

  // Notify parent about form data changes
  useEffect(() => {
    if (onFormDataChange) {
      const tipAmount = form.watch('tipAmount');
      onFormDataChange({
        timeSlot: form.watch('timeSlot'),
        totalPrice,
        extraServices: selectedExtraServices,
        ...(tipAmount !== undefined && { tipAmount }),
      });
    }
  }, [
    onFormDataChange,
    form.watch('timeSlot'),
    totalPrice,
    selectedExtraServices,
    form.watch('tipAmount'),
  ]);

  // Handle date selection
  const handleDateSelect = (date: Date | undefined) => {
    // Update local state first
    setLocalSelectedDate(date);

    // Update parent component state
    if (onSelectDate) {
      onSelectDate(date);
    }

    // Update form value
    form.setValue('date', date as Date);

    // Clear timeSlot when date changes
    if (date) {
      form.setValue('timeSlot', '');
    }
  };

  return (
    <Form {...form}>
      <form
        id="booking-form"
        onSubmit={form.handleSubmit(onSubmit)}
        className="space-y-6"
        noValidate
      >
        {/* Main service */}
        <div className="space-y-3">
          <Typography variant="h3" className="text-lg font-semibold">
            Selected Service
          </Typography>
          <BookingFormServiceCard
            id="mainService"
            name={service.name}
            description={service.description}
            duration={service.duration}
            price={service.price}
            isPrimary
          />
        </div>
        {/* Extra services */}
        <BookingFormExtraServices
          extraServices={extraServices}
          isLoadingExtraServices={isLoadingExtraServices}
          form={form}
        />

        {/* Date and Time Selection - Using the new component */}
        <BookingFormDateTimePicker
          selectedDate={localSelectedDate}
          onSelectDate={(date) => {
            handleDateSelect(date);
          }}
          availableDays={availableDays}
          availableTimeSlots={availableTimeSlots}
          selectedTimeSlot={form.watch('timeSlot')}
          onSelectTimeSlot={(timeSlot: string) => {
            form.setValue('timeSlot', timeSlot);
          }}
          service={service}
          selectedExtraServices={selectedExtraServices}
          isLoading={isLoadingTimeSlots}
          isCalendarLoading={isCalendarLoading}
          professionalTimezone={professionalTimezone}
          clientTimezone={clientTimezone}
        />

        {/* Show form errors for date and time */}
        <div className="relative">
          {!form.formState.errors.date && form.formState.errors.timeSlot && (
            <FormError
              error={form.formState.errors.timeSlot.message?.toString()}
            />
          )}
          {form.formState.errors.date && (
            <FormError error={form.formState.errors.date.message?.toString()} />
          )}
        </div>

        {/* Payment Method - Using custom BookingFormRadioGroup */}
        <div className="space-y-3">
          <Typography variant="h3" className="text-lg font-semibold">
            Payment Method
          </Typography>

          {isLoadingPaymentMethods ? (
            <div className="p-4 border rounded-md bg-muted/10 flex items-center justify-center">
              <Typography className="text-muted-foreground">
                Loading payment methods...
              </Typography>
            </div>
          ) : (
            <BookingFormRadioGroup
              options={paymentOptions}
              value={form.watch('paymentMethodId')}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                form.setValue('paymentMethodId', e.target.value)
              }
              error={form.formState.errors.paymentMethodId?.message?.toString()}
              name="paymentMethodId"
            />
          )}
        </div>
        {/* Notes */}
        <div className="space-y-3 relative">
          <Typography variant="h3" className="text-lg font-semibold">
            Additional Notes
          </Typography>

          <Textarea
            placeholder="Any special requests or notes for the professional..."
            className="resize-none min-h-[100px]"
            {...form.register('notes')}
          />

          <FormError error={form.formState.errors.notes?.message?.toString()} />
        </div>
        {/* Tip - using FormFieldWrapper and FormInput */}
        <div className="space-y-3">
          <Typography variant="h3" className="text-lg font-semibold">
            Add a Tip (Optional)
          </Typography>

          <FormFieldWrapper
            control={form.control}
            name="tipAmount"
            label="Tip Amount ($)"
          >
            {(field) => (
              <FormInput
                type="text"
                inputMode="decimal"
                placeholder="0.00"
                numericOnly
                allowDecimal
                {...field}
                onChange={(e) => {
                  const value =
                    e.target.value === '' ? 0 : Number(e.target.value);
                  field.onChange(value);
                }}
                value={field.value === 0 ? '' : (field.value?.toString() ?? '')}
              />
            )}
          </FormFieldWrapper>

          <Typography variant="muted" className="text-sm">
            Show your appreciation for exceptional service
          </Typography>
        </div>
      </form>
    </Form>
  );
}
